# Generated by Django 4.1.2 on 2022-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('edition', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('borrower', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
