# Generated by Django 4.1.2 on 2022-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_alter_book_author_alter_book_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
